# -*- encoding: utf-8 -*-

=begin
#Sezzle API

#The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

$:.push File.expand_path("../lib", __FILE__)
require "sezzle_client/version"

Gem::Specification.new do |s|
  s.name        = "sezzle_client"
  s.version     = SezzleClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Swagger-Codegen"]
  s.email       = [""]
  s.homepage    = "https://github.com/rum-and-code/sezzle_client"
  s.summary     = "Sezzle API Ruby Gem"
  s.description = "The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option. This gem was generated from the Sezzle v2 OpenAPI Specification using the Swagger Editor and modified from SwaggerClient to SezzleClient throughout."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
