=begin
#Sezzle API

#The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'date'

module SezzleClient
  class InstallmentPlan
    N4_PAY_BIWEEKLY = '4-pay-biweekly'.freeze
    N6_PAY_MONTHLY = '6-pay-monthly'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = InstallmentPlan.constants.select { |c| InstallmentPlan::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #InstallmentPlan" if constantValues.empty?
      value
    end
  end
end
