=begin
#Sezzle API

#The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for SezzleClient::BearerAuthenticationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BearerAuthenticationApi' do
  before do
    # run before each test
    @instance = SezzleClient::BearerAuthenticationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BearerAuthenticationApi' do
    it 'should create an instance of BearerAuthenticationApi' do
      expect(@instance).to be_instance_of(SezzleClient::BearerAuthenticationApi)
    end
  end

  # unit tests for post_v1_authentication
  # Get bearer authentication token
  # @param body Authentication request
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse201]
  describe 'post_v1_authentication test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
