=begin
#Sezzle API

#The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for SezzleClient::SessionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SessionApi' do
  before do
    # run before each test
    @instance = SezzleClient::SessionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionApi' do
    it 'should create an instance of SessionApi' do
      expect(@instance).to be_instance_of(SezzleClient::SessionApi)
    end
  end

  # unit tests for get_v2_session
  # Get session status
  # @param session_uuid Session UUID
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'get_v2_session test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v2_session
  # Create a new session
  # Create new customer checkout and/or tokenize customer
  # @param body Session request
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2011]
  describe 'post_v2_session test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
