=begin
#Sezzle API

#The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for SezzleClient::TokenApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TokenApi' do
  before do
    # run before each test
    @instance = SezzleClient::TokenApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TokenApi' do
    it 'should create an instance of TokenApi' do
      expect(@instance).to be_instance_of(SezzleClient::TokenApi)
    end
  end

  # unit tests for get_v2_customer_token
  # Get customer token
  # @param token Customer initiated token, e.g. generated in mobile app
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v2_customer_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v2_session_token
  # Get session token
  # @param token Merchant initiated token
  # @param [Hash] opts the optional parameters
  # @return [Token]
  describe 'get_v2_session_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
