=begin
#Sezzle API

#The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for SezzleClient::WebhooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @instance = SezzleClient::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@instance).to be_instance_of(SezzleClient::WebhooksApi)
    end
  end

  # unit tests for delete_v2_webhooks
  # Delete webhooks
  # @param webhooks_uuid Webhooks UUID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v2_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v2_webhooks
  # List webhooks
  # @param [Hash] opts the optional parameters
  # @return [Array<null>]
  describe 'get_v2_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v2_webhooks
  # Create webhooks
  # @param body Webhooks request
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2008]
  describe 'post_v2_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
