=begin
#Sezzle API

#The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

# Common files
require 'sezzle_client/api_client'
require 'sezzle_client/api_error'
require 'sezzle_client/version'
require 'sezzle_client/configuration'

# Models
require 'sezzle_client/models/address'
require 'sezzle_client/models/all_of_session_customer'
require 'sezzle_client/models/all_of_session_order'
require 'sezzle_client/models/authorization'
require 'sezzle_client/models/body'
require 'sezzle_client/models/body_1'
require 'sezzle_client/models/body_2'
require 'sezzle_client/models/body_3'
require 'sezzle_client/models/body_4'
require 'sezzle_client/models/capture'
require 'sezzle_client/models/customer'
require 'sezzle_client/models/discount'
require 'sezzle_client/models/error'
require 'sezzle_client/models/error_inner'
require 'sezzle_client/models/inline_response_200'
require 'sezzle_client/models/inline_response_200_1'
require 'sezzle_client/models/inline_response_200_2'
require 'sezzle_client/models/inline_response_200_3'
require 'sezzle_client/models/inline_response_200_4'
require 'sezzle_client/models/inline_response_200_5'
require 'sezzle_client/models/inline_response_200_6'
require 'sezzle_client/models/inline_response_200_7'
require 'sezzle_client/models/inline_response_200_8'
require 'sezzle_client/models/inline_response_200_9'
require 'sezzle_client/models/inline_response_200_order'
require 'sezzle_client/models/inline_response_201'
require 'sezzle_client/models/inline_response_201_1'
require 'sezzle_client/models/inline_response_201_1_order'
require 'sezzle_client/models/inline_response_201_1_tokenize'
require 'sezzle_client/models/installment_plan'
require 'sezzle_client/models/intent'
require 'sezzle_client/models/line_item'
require 'sezzle_client/models/link'
require 'sezzle_client/models/notification'
require 'sezzle_client/models/order'
require 'sezzle_client/models/order_authorization'
require 'sezzle_client/models/payout'
require 'sezzle_client/models/payout_inner'
require 'sezzle_client/models/price'
require 'sezzle_client/models/refund'
require 'sezzle_client/models/session'
require 'sezzle_client/models/session_cancel_url'
require 'sezzle_client/models/session_status'
require 'sezzle_client/models/token'
require 'sezzle_client/models/webhook'

# APIs
require 'sezzle_client/api/bearer_authentication_api'
require 'sezzle_client/api/customer_api'
require 'sezzle_client/api/order_api'
require 'sezzle_client/api/reports_api'
require 'sezzle_client/api/session_api'
require 'sezzle_client/api/token_api'
require 'sezzle_client/api/webhooks_api'

module SezzleClient
  class << self
    # Customize default settings for the SDK using block.
    #   SezzleClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
